<?xml version="1.0" encoding="UTF-8"?>

<project
  xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.io7m.aurantium</groupId>
    <artifactId>com.io7m.aurantium</artifactId>
    <version>1.0.0-beta0001</version>
  </parent>
  <artifactId>com.io7m.aurantium.json.schemagen</artifactId>

  <packaging>jar</packaging>
  <name>com.io7m.aurantium.json.schemagen</name>
  <description>Aurantium format (JSON schema generator)</description>
  <url>https://www.io7m.com/software/aurantium/</url>

  <properties>
    <checkstyle.skip>true</checkstyle.skip>
  </properties>

  <dependencies>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>com.io7m.aurantium.vanilla</artifactId>
      <version>${project.version}</version>
    </dependency>

    <dependency>
      <groupId>com.io7m.sumjack</groupId>
      <artifactId>com.io7m.sumjack.core</artifactId>
    </dependency>
    <dependency>
      <groupId>com.io7m.sumjack</groupId>
      <artifactId>com.io7m.sumjack.lanark</artifactId>
    </dependency>

    <dependency>
      <groupId>tools.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
    </dependency>
  </dependencies>

</project>
